---
title: "Sandbox"
author: "Joey Stanley"
date: "2023-01-18"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(janitor)

library(joeyr)
```


```{r}
raw_data <- read_csv("joey_darla.csv", show_col_types = FALSE) %>%
  clean_names() %>%
    select(speaker_id = name, everything(),
           -matches("lobanov"), -b1, -b2, -b3,-t, -beg, -end, -matches("word_trans"), -matches("_word"), -n_formants) %>%
    rename_with(ucfirst, matches("f\\d")) %>%
    rename(phoneme = vowel) %>%
    
    # Reshape 
    select(-F1, -F2, -F3) %>%
    pivot_longer(cols = matches("_percent"), 
                 names_to = c(".value", "percent"), 
                 names_pattern = "(F\\d)_(\\d\\d)") %>%
    mutate(percent = as.numeric(percent)) %>%
    filter(!is.na(F1), !is.na(F2)) %>%
    
    # OoO1 Allophones
    mutate(phoneme = arpa_to_wells(phoneme)) %>%
    code_allophones(phoneme, .fol_seg = fol_seg, .pre_seg = pre_seg) %>%
    
    # OoO2 Outliers
    group_by(speaker_id, phoneme) %>%
    filter(!find_outliers(F1, F2)) %>%
    ungroup() %>%
    
    # OoO3 Normalization
    group_by(speaker_id, phoneme) %>%
    mutate(across(.cols = c(F1, F2), 
                  .fns = c(`z` = scale, `log` = log10),
                  .names = "{.col}_{.fn}")) %>%
    # ungroup() %>%
    # norm_logmeans(c(F1_log, F2_log),
    #               .speaker_col = speaker_id,
    #               .vowel_col = phoneme) %>%
    
    # OoO4 Remove other data?
    print()
```

```{r}
make_plot <- function(df, .group) {
  ggplot(raw_data, aes(F2, F1)) + 
    # geom_point() + 
    scale_x_reverse() + 
    scale_y_reverse() + 
    stat_ellipse(aes(group = df[["allophone"]]))
}
make_plot(raw_data, "allophone")

temp <- list()
temp$name <- "allophone"
```

